### ISSUE TITLE
InvalidPathExceptions (\\?\D:\...)

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#146]
Occassionally reported InvalidPathExceptions with strange paths beginning like `\\?\D:\...`:
[29247](https://www.openmicroscopy.org/qa2/qa/feedback/29247/) , [29251](https://www.openmicroscopy.org/qa2/qa/feedback/29251/) , [29312](https://www.openmicroscopy.org/qa2/qa/feedback/29312/)

They all came from Osnabrueck. As QA access is not sorted out for @sukunis yet , I just add the full exception here (with potential sensitive bits removed).

<details>
  <summary>Stracktrace</summary>
<p>

```
java.lang.Exception: Abnormal termination due to an uncaught exception.


java.nio.file.InvalidPathException: Illegal character [?] in path at index 2: \\?\D:\Freigegeben PAINT\Collaborations\....\some.tif


	at sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)


	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)


	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)


	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)


	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)


	at java.io.File.toPath(File.java:2234)


	at org.apache.commons.io.FileUtils.isSymlink(FileUtils.java:3107)


	at org.apache.commons.io.FileUtils.sizeOfDirectory0(FileUtils.java:2618)


	at org.apache.commons.io.FileUtils.sizeOf0(FileUtils.java:2641)


	at org.apache.commons.io.FileUtils.sizeOfDirectory0(FileUtils.java:2619)


	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2599)


	at org.openmicroscopy.shoola.env.data.model.FileObject.getLength(FileObject.java:450)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileElement.getFileLength(FileElement.java:135)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileElement.getFileLengthAsString(FileElement.java:145)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.addFiles(FileSelectionTable.java:614)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.addFiles(ImportDialog.java:424)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.showLocationDialog(ImportDialog.java:432)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.propertyChange(ImportDialog.java:1726)


	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)


	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)


	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)


	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)


	at java.awt.Component.firePropertyChange(Component.java:8448)


	at javax.swing.JComponent.firePropertyChange(JComponent.java:4491)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.actionPerformed(FileSelectionTable.java:698)


	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)


	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)


	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)


	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)


	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)


	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)


	at java.awt.Component.processMouseEvent(Component.java:6533)


	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)


	at java.awt.Component.processEvent(Component.java:6298)


	at java.awt.Container.processEvent(Container.java:2237)


	at java.awt.Component.dispatchEventImpl(Component.java:4889)


	at java.awt.Container.dispatchEventImpl(Container.java:2295)


	at java.awt.Component.dispatchEvent(Component.java:4711)


	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)


	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)


	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)


	at java.awt.Container.dispatchEventImpl(Container.java:2281)


	at java.awt.Window.dispatchEventImpl(Window.java:2746)


	at java.awt.Component.dispatchEvent(Component.java:4711)


	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)


	at java.awt.EventQueue.access$500(EventQueue.java:97)


	at java.awt.EventQueue$3.run(EventQueue.java:709)


	at java.awt.EventQueue$3.run(EventQueue.java:703)


	at java.security.AccessController.doPrivileged(Native Method)


	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)


	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)


	at java.awt.EventQueue$4.run(EventQueue.java:731)


	at java.awt.EventQueue$4.run(EventQueue.java:729)


	at java.security.AccessController.doPrivileged(Native Method)


	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)


	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)


	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)


	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)


	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)


	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)


	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)


	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


Abnormal termination due to an uncaught exception.
```
</p>
</details>

**Comment by dominikl** [comment]
More QAs:
- [29451](https://www.openmicroscopy.org/qa2/qa/feedback/29451/)

**Comment by dominikl** [comment]
Latest QA [29470](https://www.openmicroscopy.org/qa2/qa/feedback/29470/):
<details>
  <summary>Stracktrace (full path string anoymized)</summary>
<p>

```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.nio.file.InvalidPathException: Illegal character [?] in path at index 2: \\?\D:\Freigegeben PAINT\Collaborations\SOME_PATH\SOME.tif
	at sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.io.File.toPath(File.java:2234)
	at org.apache.commons.io.FileUtils.isSymlink(FileUtils.java:3107)
	at org.apache.commons.io.FileUtils.sizeOfDirectory0(FileUtils.java:2618)
	at org.apache.commons.io.FileUtils.sizeOf0(FileUtils.java:2641)
	at org.apache.commons.io.FileUtils.sizeOfDirectory0(FileUtils.java:2619)
	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2599)
	at org.openmicroscopy.shoola.env.data.model.FileObject.getLength(FileObject.java:450)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileElement.getFileLength(FileElement.java:135)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileElement.getFileLengthAsString(FileElement.java:145)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.addFiles(FileSelectionTable.java:614)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.addFiles(ImportDialog.java:426)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.showLocationDialog(ImportDialog.java:434)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.propertyChange(ImportDialog.java:1728)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
	at java.awt.Component.firePropertyChange(Component.java:8448)
	at javax.swing.JComponent.firePropertyChange(JComponent.java:4491)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.actionPerformed(FileSelectionTable.java:698)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Abnormal termination due to an uncaught exception.
java.nio.file.InvalidPathException: Illegal character [?] in path at index 2: \\?\D:\Freigegeben PAINT\Collaborations\Tim Wedeking\191205\190205_IFNAR_1_2_KO_Rab7_Alexa647_IFNa_DY547_LAMP1_Alexa488\2\Deskewed\191205_IFNAR_1_2_KO_Rab7_Alexa647_IFNa_DY547_LAMP1_Alexa488_z300_2_CamA_ch0_stack0000_642nm_0000000msec_0013137116msecAbs_deskewed_REG488.tif
	at sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.io.File.toPath(File.java:2234)
	at org.apache.commons.io.FileUtils.isSymlink(FileUtils.java:3107)
	at org.apache.commons.io.FileUtils.sizeOfDirectory0(FileUtils.java:2618)
	at org.apache.commons.io.FileUtils.sizeOf0(FileUtils.java:2641)
	at org.apache.commons.io.FileUtils.sizeOfDirectory0(FileUtils.java:2619)
	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2599)
	at org.openmicroscopy.shoola.env.data.model.FileObject.getLength(FileObject.java:450)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileElement.getFileLength(FileElement.java:135)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileElement.getFileLengthAsString(FileElement.java:145)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.addFiles(FileSelectionTable.java:614)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.addFiles(ImportDialog.java:426)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.showLocationDialog(ImportDialog.java:434)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.propertyChange(ImportDialog.java:1728)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
	at java.awt.Component.firePropertyChange(Component.java:8448)
	at javax.swing.JComponent.firePropertyChange(JComponent.java:4491)
	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.actionPerformed(FileSelectionTable.java:698)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0"
	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.showErrorDialog(UserNotifierImpl.java:189)
	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyError(UserNotifierImpl.java:289)
	at org.openmicroscopy.shoola.env.AbnormalExitHandler.doTermination(AbnormalExitHandler.java:147)
	at org.openmicroscopy.shoola.env.AbnormalExitHandler.terminate(AbnormalExitHandler.java:85)
	at org.openmicroscopy.shoola.env.RootThreadGroup.uncaughtException(RootThreadGroup.java:69)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
</p>
</details>

\cc @sukunis

**Comment by joshmoore** [comment]
Is something like this useful? https://stackoverflow.com/a/43973911/56887

**Comment by dominikl** [comment]
Two more, but again no further information... [29750](https://www.openmicroscopy.org/qa2/qa/feedback/29750/) [29749](https://www.openmicroscopy.org/qa2/qa/feedback/29749/)

**Comment by dominikl** [comment]
[QA 30960](https://www.openmicroscopy.org/qa2/qa/feedback/30960/) ... but if nobody provides any information how to trigger the bug, I can't fix it :-/

**Comment by dominikl** [comment]
[QA 30978](https://www.openmicroscopy.org/qa2/qa/feedback/30978/)

**Comment by dominikl** [comment]
[QA 31310](https://www.openmicroscopy.org/qa2/qa/feedback/31310/)

**Comment by sukunis** [comment]
I finally have an idea what could create this cryptic path `\\?\D:\`. But to verify the idea I need access to the error messages in the QA system, unfortunately I can't access the detailed linked error messages.

**Comment by jburel** [comment]
@sukunis the stacktrace is the only thing we have, nobody indicates how the problem gets triggered when submitting the error.

**Comment by pwalczysko** [comment]
I think @sukunis does not have the stacktrace :)

Please see below, does it help ?

<details>

```


java.lang.Exception: Abnormal termination due to an uncaught exception.


java.nio.file.InvalidPathException: Illegal character [?] in path at index 2: \\?\D:\Users\BP\Pollmann\2-11-2022\11-2-22_HeLa_ALFA-LepR-b_aALFA-Cy3B_Dy752 10nM Leptin + 5nM aLeptinR Cy5 cell8 (same cell as cell 8 wo aLpetinR)_1\11-2-22_HeLa_ALFA-LepR-b_aALFA-Cy3B_Dy752 10nM Leptin + 5nM aLeptinR Cy5 cell8 (same cell as cell 8 wo aLpetinR)_1_MMStack_Default.ome.tif


	at sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)


	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)


	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)


	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)


	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)


	at java.io.File.toPath(File.java:2234)


	at org.apache.commons.io.FileUtils.isSymlink(FileUtils.java:3107)


	at org.apache.commons.io.FileUtils.sizeOfDirectory0(FileUtils.java:2618)


	at org.apache.commons.io.FileUtils.sizeOf0(FileUtils.java:2641)


	at org.apache.commons.io.FileUtils.sizeOfDirectory0(FileUtils.java:2619)


	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2599)


	at org.openmicroscopy.shoola.env.data.model.FileObject.getLength(FileObject.java:464)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileElement.getFileLength(FileElement.java:135)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileElement.getFileLengthAsString(FileElement.java:145)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.addFiles(FileSelectionTable.java:614)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.addFiles(ImportDialog.java:428)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.showLocationDialog(ImportDialog.java:436)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.propertyChange(ImportDialog.java:1758)


	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)


	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)


	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)


	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)


	at java.awt.Component.firePropertyChange(Component.java:8448)


	at javax.swing.JComponent.firePropertyChange(JComponent.java:4491)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.actionPerformed(FileSelectionTable.java:698)


	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)


	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)


	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)


	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)


	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)


	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)


	at java.awt.Component.processMouseEvent(Component.java:6533)


	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)


	at java.awt.Component.processEvent(Component.java:6298)


	at java.awt.Container.processEvent(Container.java:2237)


	at java.awt.Component.dispatchEventImpl(Component.java:4889)


	at java.awt.Container.dispatchEventImpl(Container.java:2295)


	at java.awt.Component.dispatchEvent(Component.java:4711)


	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)


	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)


	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)


	at java.awt.Container.dispatchEventImpl(Container.java:2281)


	at java.awt.Window.dispatchEventImpl(Window.java:2746)


	at java.awt.Component.dispatchEvent(Component.java:4711)


	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)


	at java.awt.EventQueue.access$500(EventQueue.java:97)


	at java.awt.EventQueue$3.run(EventQueue.java:709)


	at java.awt.EventQueue$3.run(EventQueue.java:703)


	at java.security.AccessController.doPrivileged(Native Method)


	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)


	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)


	at java.awt.EventQueue$4.run(EventQueue.java:731)


	at java.awt.EventQueue$4.run(EventQueue.java:729)


	at java.security.AccessController.doPrivileged(Native Method)


	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)


	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)


	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)


	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)


	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)


	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)


	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)


	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


Abnormal termination due to an uncaught exception.


java.nio.file.InvalidPathException: Illegal character [?] in path at index 2: \\?\D:\Users\BP\Pollmann\2-11-2022\11-2-22_HeLa_ALFA-LepR-b_aALFA-Cy3B_Dy752 10nM Leptin + 5nM aLeptinR Cy5 cell8 (same cell as cell 8 wo aLpetinR)_1\11-2-22_HeLa_ALFA-LepR-b_aALFA-Cy3B_Dy752 10nM Leptin + 5nM aLeptinR Cy5 cell8 (same cell as cell 8 wo aLpetinR)_1_MMStack_Default.ome.tif


	at sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)


	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:111)


	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)


	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)


	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)


	at java.io.File.toPath(File.java:2234)


	at org.apache.commons.io.FileUtils.isSymlink(FileUtils.java:3107)


	at org.apache.commons.io.FileUtils.sizeOfDirectory0(FileUtils.java:2618)


	at org.apache.commons.io.FileUtils.sizeOf0(FileUtils.java:2641)


	at org.apache.commons.io.FileUtils.sizeOfDirectory0(FileUtils.java:2619)


	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2599)


	at org.openmicroscopy.shoola.env.data.model.FileObject.getLength(FileObject.java:464)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileElement.getFileLength(FileElement.java:135)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileElement.getFileLengthAsString(FileElement.java:145)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.addFiles(FileSelectionTable.java:614)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.addFiles(ImportDialog.java:428)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.showLocationDialog(ImportDialog.java:436)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.propertyChange(ImportDialog.java:1758)


	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)


	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)


	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)


	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)


	at java.awt.Component.firePropertyChange(Component.java:8448)


	at javax.swing.JComponent.firePropertyChange(JComponent.java:4491)


	at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.actionPerformed(FileSelectionTable.java:698)


	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)


	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)


	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)


	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)


	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)


	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)


	at java.awt.Component.processMouseEvent(Component.java:6533)


	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)


	at java.awt.Component.processEvent(Component.java:6298)


	at java.awt.Container.processEvent(Container.java:2237)


	at java.awt.Component.dispatchEventImpl(Component.java:4889)


	at java.awt.Container.dispatchEventImpl(Container.java:2295)


	at java.awt.Component.dispatchEvent(Component.java:4711)


	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)


	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)


	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)


	at java.awt.Container.dispatchEventImpl(Container.java:2281)


	at java.awt.Window.dispatchEventImpl(Window.java:2746)


	at java.awt.Component.dispatchEvent(Component.java:4711)


	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)


	at java.awt.EventQueue.access$500(EventQueue.java:97)


	at java.awt.EventQueue$3.run(EventQueue.java:709)


	at java.awt.EventQueue$3.run(EventQueue.java:703)


	at java.security.AccessController.doPrivileged(Native Method)


	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)


	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)


	at java.awt.EventQueue$4.run(EventQueue.java:731)


	at java.awt.EventQueue$4.run(EventQueue.java:729)


	at java.security.AccessController.doPrivileged(Native Method)


	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)


	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)


	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)


	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)


	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)


	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)


	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)


	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


Exception in thread "AWT-EventQueue-0"


	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.showErrorDialog(UserNotifierImpl.java:195)


	at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyError(UserNotifierImpl.java:295)


	at org.openmicroscopy.shoola.env.AbnormalExitHandler.doTermination(AbnormalExitHandler.java:147)


	at org.openmicroscopy.shoola.env.AbnormalExitHandler.terminate(AbnormalExitHandler.java:85)


	at org.openmicroscopy.shoola.env.RootThreadGroup.uncaughtException(RootThreadGroup.java:69)


	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)


	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)


	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)


	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)


	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)


	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)


	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

</details>

**Comment by pwalczysko** [comment]
> I can't access the detailed linked error messages.

@sukunis Or maybe you mean that you need the bit which was edited out as it is a sensitive info ?

**Comment by dominikl** [comment]
Would be nice to find out what causes this error. Unfortunately nobody tells us what they did to trigger it.

**Comment by sukunis** [comment]
I can reproduce the error when trying to import data stored in a directory with a path length >256 on an external drive. It would be interesting to know if you can reproduce this on Linux or if it is a Windows specific problem?

**Comment by dominikl** [comment]
Ah, thank you very much. I'll try to replicate it that way...

**Comment by sukunis** [comment]
The paths are created by Micromanager on our System...

**Comment by sukunis** [comment]
maybe this could be helpful: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

**Comment by jburel** [comment]
Fixed in https://github.com/ome/omero-insight/pull/328 (version 5.8.0)

**Comment by dominikl** [comment]
Looks like it's not completely fixed: [QA 33044](https://www.openmicroscopy.org/qa2/qa/feedback/33044/)
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.nio.file.InvalidPathException: Illegal character [?] in path at index 2: \\?\Z:\INCell_Data_Analyed\SCAR_BEV_Jones BEV Test\220805_SCAR_BEV_E1_40X_RS\.imaris_cache\a - 1(fld 001 wv 405 - blue z 01)_a_well  a - 1 field  0 channel 0 scar_bev_singleslide_40x_is_gv_well  a - 1 field  143 channel 3 scar_bev_singleslide_40x_is.ims\thumbretry_256_0.xml
	at sun.nio.fs.WindowsPathParser.nextSlash(WindowsPathParser.java:212)
...
```
